{ config, lib, pkgs, ... }:

{
  
  # include NixOS-WSL modules this will require --impure in the nixosrebuild switch command
  imports = [
    <nixos-wsl/modules>
  ];

  wsl = {
    enable = true;

    # Path integration
    # wslConf.interop.appendWindowsPath = true; # Append Windows PATH to NixOS PATH
    wslConf.automount.root = "/mnt"; # Mount Windows drives to /mnt/c, /mnt/d, etc.
    
    # Make Windows executables visible and runnable from WSL
    interop.includePath = true;
    interop.register = true;

    # /etc/wsl.conf settings generated by NixOS-WSL
    wslConf = {
      interop.enabled = true;
      interop.appendWindowsPath = true;
    };

  };

  fonts = {
    enableDefaultPackages = true;
    packages = with pkgs; [
      nerd-fonts.mononoki
    ];
    fontconfig = {
      enable = true;
      defaultFonts = {
        monospace = [ "Mononoki Nerd Font" ];
        sansSerif = [ "Mononoki Nerd Font" ];
        serif = [ "Mononoki Nerd Font" ];
      };
    };
  };

  # --- Standard NixOS Settings ---
  networking.hostName = "nixos-wsl";
  
  # Enable experimental features (necessary for Flakes)
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  
  programs.zsh.enable    = true;
  users.defaultUserShell = pkgs.zsh;

  services.dbus.enable = true;

  # System Packages
  environment.systemPackages = with pkgs; [
    #general utils
    alacritty
    git
    xclip
    jq
    unzip
    fzf
    zsh
    tmux
    ripgrep
    htop
    bzip2
    gnupg
    gnumake
    neovim
    stow
    gh
    github-copilot-cli
    zoxide
    checkov
    terraform

    # go
    go
    gotools

    # rust
    rustc
    cargo

    # zig
    zig

    # node
    nodejs_22

    # C
    clang-tools
    cmake
    cppcheck
    codespell
    conan
    doxygen
    gtest
    lcov
    libgcc
    vcpkg
    vcpkg-tool
    gcc

    #network
    lsof
    bind

    # JAVA
    jdk17
    groovy
  ];

  # Allow unfree packages (e.g. VS Code, Chrome, Slack)
  nixpkgs.config.allowUnfree = true;

  system.stateVersion = "25.05"; # Did you read the comment?
}
