{ config, lib, pkgs, ... }:

{
  # include NixOS-WSL modules this will require --impure in the nixosrebuild switch command
  imports = [
    <nixos-wsl/modules>
  ];

  wsl = {
    enable = true;

    # Path integration
    # wslConf.interop.appendWindowsPath = true; # Append Windows PATH to NixOS PATH
    wslConf.automount.root = "/mnt"; # Mount Windows drives to /mnt/c, /mnt/d, etc.
    
    # Make Windows executables visible and runnable from WSL
    interop.includePath = true;
    interop.register = true;

    # /etc/wsl.conf settings generated by NixOS-WSL
    wslConf = {
      interop.enabled = true;
      interop.appendWindowsPath = true;
    };
  };

  virtualisation.podman = {
    enable = true;
    dockerCompat = true; # Makes `docker` CLI point to podman
  };

  fonts = {
    enableDefaultPackages = true;
    packages = with pkgs; [
      nerd-fonts.mononoki
    ];
    fontconfig = {
      enable = true;
      defaultFonts = {
        monospace = [ "Mononoki Nerd Font" ];
        sansSerif = [ "Mononoki Nerd Font" ];
        serif = [ "Mononoki Nerd Font" ];
      };
    };
  };

  # --- Standard NixOS Settings ---
  networking.hostName = "nixos-wsl";
  
  # Enable experimental features (necessary for Flakes)
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
  
  programs.zsh.enable    = true;
  users.defaultUserShell = pkgs.zsh;

  services.dbus.enable = true;

  # --- Podman Configuration ---
  virtualisation.podman = {
    enable = true;
    # Create a `docker` alias for podman, allowing tools that expect docker to work
    dockerCompat = true;
    # Required for containers under podman-compose to be able to talk to each other
    defaultNetwork.settings.dns_enabled = true;
  };

  # System Packages
  environment.systemPackages = with pkgs; [
    # General utils
    terragrunt
    alacritty
    git
    xclip
    jq
    unzip
    fzf
    zsh
    tmux
    ripgrep
    htop
    bzip2
    gnupg
    gnumake
    neovim
    stow
    gh
    github-copilot-cli
    zoxide
    checkov
    terraform
    yazi
    kubelogin
    openssl
    oras
    swaks
    podman-compose
    kompose
    worktrunk

    # Go
    go
    gotools
    goreleaser

    # Rust
    rustc
    cargo

    # Zig
    zig

    # Node
    nodejs_22

    # C / C++
    clang-tools
    cmake
    cppcheck
    codespell
    conan
    doxygen
    gtest
    lcov
    libgcc
    vcpkg
    vcpkg-tool
    gcc

    # Network
    lsof
    bind

    # Java
    jdk17
    groovy

    # Containers
    podman-compose # Added to parse and run your compose file
  ];

  boot.kernelModules = [ 
    "vhci-hcd" 
    "cdc-acm" 
    "usbserial" 
  ];
  
  # Allow unfree packages (e.g. VS Code, Chrome, Slack)
  nixpkgs.config.allowUnfree = true;

  system.stateVersion = "25.05"; # Did you read the comment?
}
