-- vim.api.nvim_create_user_command(
--   'ToggleMarkdownRender',
--   function()
--     local render_markdown = require('render-markdown')
--     if render_markdown.is_rendering() then
--       render_markdown.stop()
--       vim.notify('Markdown render stopped', vim.log.level.INFO)
--     else
--       render_markdown.start()
--       vim.notify('Markdown render started', vim.log.level.INFO)
--     end
--   end,
--   {}
-- )
