format = """
$directory\
$git_branch\
$git_status\
$aws\
$azure\
$kubernetes\
$line_break\
$character"""

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[aws]
symbol = "󰸏" 
format = ' [$symbol ($profile)(\[$duration\])]($style)  '

[azure]
disabled = false
symbol = "󰠅"
format = '[$symbol ($subscription)]($style)  '

[kubernetes]
disabled = false
symbol = "󱃾"
format = '[$symbol $context(10)]($style)  '



# format = """
# [](#565f89)\
# $username\
# [](bg:#414868 fg:#565f89)\
# $directory\
# [](fg:#414868 bg:#7dcfff)\
# $git_branch\
# $git_status\
# [](fg:#7dcfff bg:#b4f9f8)\
# [](fg:#b4f9f8 bg:#ff9e64)\
# [](fg:#ff9e64 bg:#f7768e)\
# $time\
# [](fg:#f7768e)\
# \n$character\n"""
#
# command_timeout = 5000
# # Disable the blank line at the start of the prompt
# # add_newline = false
#
# # You can also replace your username with a neat symbol like  to save some space
# [username]
# show_always = true
# style_user = "bg:#565f89"
# style_root = "bg:#565f89"
# format = '[$user ]($style)'
#
# [directory]
# style = "bg:#414868"
# format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"
#
# [git_branch]
# symbol = ""
# style = "fg:#414868 bg:#7dcfff"
# format = '[ $symbol $branch ]($style)'
#
# [git_status]
# style = "fg:#414868 bg:#7dcfff"
# format = '[$all_status$ahead_behind ]($style)'
#
# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "fg:#414868 bg:#f7768e"
# format = '[ $time ]($style)'
